# Generated by Django 4.1.7 on 2024-02-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_project_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
