# Generated by Django 4.1.7 on 2024-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_urlshortener_original_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlshortener",
            name="original_url",
            field=models.URLField(max_length=2000),
        ),
    ]
